name: 'Pull Request Sticky Footer'
description: 'Keep a concise custom message at the bottom of your PR description. Helps avoid superfluous comments.'
author: 'kyranjamie'
inputs:
  header:
    description: 'Markdown text you want to stick at the bottom of your PR'
    required: true
  destination_branch:
    description: 'Base branch of the PR. Default is master'
    default: 'master'
    required: false
  GITHUB_TOKEN:
    description: 'set secrets.GITHUB_TOKEN here'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'git-pull-request'
  color: 'yellow'
